#!/bin/bash
set -e

YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m' # Sem cor

echo -e "${YELLOW}[INFO] Copiando arquivos de configuração...${NC}"

# Garante que os diretórios de destino existem
mkdir -p ~/.config
mkdir -p ~/.local/share
mkdir -p ~/.fonts

# Copiar configurações
cp -r config/alacritty ~/.config/
cp -r config/bat ~/.config/
cp -r config/nvim ~/.config/
cp -r config/tmux ~/.config/
cp -r share/nvim ~/.local/share/
cp -r fonts ~/.fonts
cp -r oh-my-zsh-custom/* ~/.oh-my-zsh/custom/
cp .p10k.zsh .zshrc ~/

echo -e "${GREEN}[OK] Configurações copiadas com sucesso.${NC}"
echo -e "${YELLOW}[INFO] Execute 'source ~/.zshrc' para aplicar as configurações no shell atual.${NC}"
echo -e "${YELLOW}[INFO] Abra uma sessão tmux, execute 'tmux source ~/.config/tmux/tmux.conf' e pressione 'prefix + I' para instalar os plugins manualmente.${NC}"
